CREATE TABLE "CLIENTS" (
  "ID" int NOT NULL AUTO_INCREMENT,
  "SHARED_KEY" varchar(200) DEFAULT NULL,
  "NAME" varchar(200) DEFAULT NULL,
  "EMAIL" varchar(200) DEFAULT NULL,
  "PHONE" varchar(200) DEFAULT NULL,
  "DATEADDED" date DEFAULT NULL,
  PRIMARY KEY ("ID")
);